# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  lane :buildIPA do

# 有options 参数 一直不明白options 怎么来的原来需要外面传入。
#     fastlane buildIPA project:GMUtil version:0.1.4


# identifier = get_info_plist_value(path: "./Info.plist", key: "CFBundleIdentifier")

    #development

    # Download the provisioning profile for the app
    # sigh(output_path: "./fastlane/profiles") # Distribution Profile

    # Download the provisioning profile
    # sigh(
    #   output_path: "./fastlane/profiles",
    #   app_identifier: "com.nextxnow.kuduroutines"
    # )
     match(
      git_url : https://github.com/geasscode/CIProject.git
      app_identifier: "com.geass.CIProject",
      username "geasscode@outlook.com",
      type: "adhoc",git_branch:"dev",
      git_branch: "dev"
      )
    # cert(development: true,username: ENV["FASTLANE_USER"],keychain_password: ENV["FASTLANE_PASSWORD"])

    #   sigh(
    #   adhoc: true,
    #   force: true,
    #   #username: ENV["FASTLANE_USER"],
    #   app_identifier:"com.geass.CITest",

    # )
    # Helper.log.info "Updategit_url "https://github.com/geasscode/CITest.git"
    build_name = "CIProject_v#{get_version_number}"

    gym(
      configuration: "Release",
      scheme: "CIProject",
      include_bitcode: false,
      silent: true,
      clean: true,
      output_directory: "~/Documents/buildIPA/",
      output_name: "#{build_name}.ipa",
      # export_method:"ad-hoc,enterprise,appstore,development"
      # include_symbols: true,
      # sdk: "iphoneos10.1",
      export_method:"ad-hoc",
      use_legacy_build_api: true
      )
  end


  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    # # Build your app - more options available
    #deliver(force: true)
    # frameit

    buildIPA
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
